version: '3.7'
services:
  frontend:
    build:
      context: .
    command: yarn dev
    environment:
      - ADS_PORT=${ADS_PORT}
      - DISCOUNTS_PORT=${DISCOUNTS_PORT}
      - ADS_ROUTE=${ADS_ROUTE}
      - DISCOUNTS_ROUTE=${DISCOUNTS_ROUTE}
    volumes:
      - "./site:/storedog-app/site"
    ports:
      - 3000:3000
    networks:
      - storedog-backend_storedog-net

networks:
  storedog-backend_storedog-net:
    external: true
