version: '3.7'
services:
  frontend:
    build:
      context: .
    command: yarn dev
    volumes:
      - "./site:/storedog-app/site"
    ports:
      - 3000:3000
    networks:
      - storedog-backend_storedog-net
  nginx:
    restart: always
    build:
      context: ./packages/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    labels:
      com.datadoghq.frontend.logs: '[{"source": "nginx", "service": "nginx"}]'
    networks:
      - storedog-backend_storedog-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  storedog-backend_storedog-net:
    external: true
