version: '3.7'
services:
  frontend:
    build:
      context: ./services/frontend
    command: yarn dev
    volumes:
      - "./services/frontend/site:/storedog-app/site"
    ports:
      - 3000:3000
    networks:
      - storedog-backend_storedog-net
    environment:
      - "NEXT_PUBLIC_DD_CLIENT_TOKEN=${DD_CLIENT_TOKEN}"
      - "NEXT_PUBLIC_DD_APPLICATION_ID=${APP_ID}"
  nginx:
    build:
      context: ./services/nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "nginx"}]'
    networks:
      - storedog-backend_storedog-net

networks:
  storedog-backend_storedog-net:
    external: true
