version: '3.7'
services:
  frontend:
    build:
      context: .
    command: yarn dev
    ports:
      - 3000:3000
    networks:
      - storedog-backend_storedog-net

networks:
  storedog-backend_storedog-net:
    external: true
